services:
  init:
    image: colonyos/colonies:v1.9.0
    volumes:
      - configuration:/configuration
      - ./init-entrypoint.sh:/init-entrypoint.sh
    command: ["/init-entrypoint.sh"]

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    hostname: timescaledb
    environment:
      POSTGRES_USER: colonies
      PGDATA: /var/lib/postgresql/data
      TZ: Europe/Stockholm
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - configuration:/configuration
      - ./timescaledb-entrypoint.sh:/timescaledb-entrypoint.sh
    depends_on:
      init:
        condition: service_completed_successfully
    entrypoint: ["/bin/bash", "./timescaledb-entrypoint.sh"]

  colonyos:
    image: colonyos/colonies:v1.9.0
    hostname: colonyos
    environment:
      COLONIES_SERVER_TLS: false
      COLONIES_SERVER_PORT: 50080
      COLONIES_SERVER_HOST: colonyos
      COLONIES_DB_HOST: timescaledb
      COLONIES_DB_USER: colonies
      TZ: Europe/Stockholm
    depends_on:
      - timescaledb
    volumes:
      - configuration:/configuration
      - ./colonies-entrypoint.sh:/colonies-entrypoint.sh
    entrypoint: ["/bin/sh", "./colonies-entrypoint.sh"]

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      COLONIES_SERVER_TLS: false
      COLONIES_SERVER_PORT: 50080
      COLONIES_SERVER_HOST: colonyos
      COLONIES_COLONY_NAME: dev
      TZ: Europe/Stockholm
    volumes:
      - ../:/workspaces
      - configuration:/configuration
    depends_on:
      - timescaledb
      - colonyos

volumes:
  timescaledb_data:
  configuration:
